load("//tensorflow/core:platform/default/build_config.bzl", "tf_proto_library_py", "tf_proto_library")

tf_proto_library(
	name = "estimator_config",
	srcs = [
		"estimator_config.proto",
	],
	visibility = ["//tts:__subpackages__"]
)
