load("//tensorflow/core:platform/default/build_config.bzl", "tf_proto_library_py", "tf_proto_library")

tf_proto_library(
	name = "config_proto",
	srcs = [
		"config.proto",
	],
	visibility = ["//tensorflow/contrib/recsys:__subpackages__"]
)
