description: "test feature column schema"
column_config: {
	name: "int32"
	real_valued: {
		dimension: 10
    dtype: DT_INT32
	}
	include: true
}
column_config: {
	name: "label"
	real_valued: {
		dimension: 1
    dtype: DT_INT64
	}
	include: true
}
column_config: {
	name: "float"
	real_valued: {
		dimension: 20
    dtype: DT_FLOAT
	}
	include: true
}
# this feature column will be discarded.
column_config: {
	name: "real_valued_discarded"
	real_valued: {
		dimension: 20
    dtype: DT_DOUBLE
	}
	include: false
}
column_config: {
	name: "integerized"
	integerized: {
		bucket_size: 10
		combiner: COMBINER_TYPE_SUM
		dtype: DT_INT32
	}
	include: true
}
column_config: {
	name: "hash_bucket"
	hash_bucket: {
		hash_bucket_size: 5000
		combiner: COMBINER_TYPE_MEAN
		dtype: DT_INT64
	}
	include: true
}
column_config: {
	name: "embedding"
	embedding: {
		dimension: 50
		combiner: COMBINER_TYPE_SQRT
	}
	dependency: "hash_bucket"
	include: true
}
